dist: trusty
sudo: false
language: php

matrix:
  include:
    - php: 7.0
      env: ILLUMINATE_VERSION=5.4.* COMPOSER_ARGS="--prefer-lowest"
    - php: 7.0
      env: ILLUMINATE_VERSION=5.4.*
    - php: 7.1
      env: ILLUMINATE_VERSION=5.4.*
    - php: 7.2
      env: ILLUMINATE_VERSION=5.4.*
    - php: 7.0
      env: ILLUMINATE_VERSION=5.5.*
    - php: 7.1
      env: ILLUMINATE_VERSION=5.5.* ANALYSIS=true
    - php: 7.2
      env: ILLUMINATE_VERSION=5.5.*
    #- php: 7.1
    #  env: ILLUMINATE_VERSION=5.6.*
    #- php: 7.2
    #  env: ILLUMINATE_VERSION=5.6.*

before_install:
  - composer self-update
  - composer require "illuminate/database:${ILLUMINATE_VERSION}" --no-update
  - composer require "illuminate/support:${ILLUMINATE_VERSION}" --no-update

install:
  - composer update $COMPOSER_ARGS --no-interaction --prefer-dist

script:
  - if [[ "${ANALYSIS}" == 'true' ]]; then php vendor/bin/phpcs ; fi
  - if [[ "${ANALYSIS}" == 'true' ]]; then php vendor/bin/phpunit --coverage-clover=clover.xml ; fi
  - if [[ "${ANALYSIS}" != 'true' ]]; then php vendor/bin/phpunit ; fi

after_script:
  - if [[ "${ANALYSIS}" == 'true' ]]; then composer require satooshi/php-coveralls:~1.0 ; fi
  - if [[ "${ANALYSIS}" == 'true' ]]; then php vendor/bin/coveralls --coverage_clover=clover.xml -v ; fi
